export const editorsChoice: string;
export const row: string;
export const content: string;
export const contentLoading: string;
export const searchButton: string;
export const loadingText: string;
export const startup: string;
export const topNav: string;
export const iconCircle: string;
