export const home = require('./home.svg')
export const editorsChoice = require('./editors_choice.svg')
export const play = require('./play.svg')
export const pause = require('./pause.svg')
export const audio = require('./audio.svg')
export const settings = require('./settings.svg')
